version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraftserver
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"

      #TYPE: CURSEFORGE
      #TYPE: AUTO_CURSEFORGE
      #VERSION: 1.20.1
      #FORGE_VERSION: 47.3.0
      #CF_SERVER_MOD: /modpacks/server-1.1.3.zip #ATM9-Skyblocks
      #CF_SERVER_MOD: /modpacks/ATM9-0.2.56.zip
      #CF_SERVER_MOD: /modpacks/Server-Files-0.2.56.zip

      TYPE: FORGE
      VERSION: 1.20.1
      FORGE_VERSION: 47.3.0
      GENERIC_PACK: /modpacks/server-1.1.3.zip #ATM9-Skyblocks
      #GENERIC_PACK: /modpacks/ATM9-0.2.56.zip #ATM9
      #GENERIC_PACK: /modpacks/Server-Files-0.2.56.zip
      #GENERIC_PACK: https://mediafilez.forgecdn.net/files/5226/700/Server-Files-0.2.56.zip
      #REMOVE_OLD_MODS: "TRUE"

      MEMORY: "48G"

      ENABLE_WHITELIST: "TRUE"
      WHITELIST: |
        "8a30e43b-73c2-49d3-bccc-ad50d8dbb928"
        "575f63e4-a0b2-4718-850d-d91f21f080af"
      OP: |
        "8a30e43b-73c2-49d3-bccc-ad50d8dbb928"
        "575f63e4-a0b2-4718-850d-d91f21f080af"
      
      #"D3F1L3"
      #"PlanetHEOS0X"
      
      #"8a30e43b-73c2-49d3-bccc-ad50d8dbb928"
      #"575f63e4-a0b2-4718-850d-d91f21f080af"

      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "OsteBoys"
      MODE: "survival"
      DIFFICULTY: "easy"
      PVP: "FALSE"
      ALLOW_FLIGHT: "TRUE"
      #LEVEL_TYPE: "biomesoplenty"
      CUSTOM_SERVER_PROPERTIES: |
        allow-cheats=true
        level-name=OsteBoys

    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./modpacks:/modpacks:ro

volumes:
  data:
