version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraftserver
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"

      #TYPE: CURSEFORGE
      #VERSION: 1.20.1
      #FORGE_VERSION: 47.2.20
      #CF_SERVER_MOD: /modpacks/ATM9-0.2.56.zip
      #CF_SERVER_MOD: /modpacks/Server-Files-0.2.56.zip

      TYPE: FORGE
      VERSION: 1.20.1
      FORGE_VERSION: 47.2.20
      #GENERIC_PACK: /modpacks/ATM9-0.2.56.zip
      #GENERIC_PACK: /modpacks/Server-Files-0.2.56.zip
      #GENERIC_PACK: https://mediafilez.forgecdn.net/files/5226/700/Server-Files-0.2.56.zip
      REMOVE_OLD_MODS: "TRUE"

      MEMORY: "32G"

      ENABLE_WHITELIST: "FALSE"
      #WHITELIST: |
        #"D3F1L3"
        #"PlanetHEOS0X"
      OP: |
        "D3F1L3"
        "PlanetHEOS0X"

      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SERVER_NAME: "OsteBoys-Vanilla"
      MODE: "survival"
      DIFFICULTY: "easy"
      PVP: "FALSE"
      ALLOW_FLIGHT: "TRUE"
      #LEVEL_TYPE: "biomesoplenty"
      CUSTOM_SERVER_PROPERTIES: |
        allow-cheats=true
        level-name=OsteBoys-Vanilla

    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./modpacks:/modpacks:ro

volumes:
  data:
