version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    container_name: minecraftserver
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      EULA: "TRUE"
      TYPE: FORGE

      VERSION: 1.20.1
      FORGE_VERSION: 47.2.20

      MEMORY: "8G"
      
      SERVER_NAME: "OsteBoys"
      MODE: "survival"
      DIFFICULTY: "easy"
      PVP: "FALSE"
      ALLOW_FLIGHT: "TRUE"
      GENERIC_PACK: /modpacks/ATM9-0.2.56.zip
      REMOVE_OLD_MODS: "TRUE"

      ENABLE_WHITELIST: "FALSE"
      OP: |
        "D3F1L3"
        "PlanetHEOS0X"

      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      CUSTOM_SERVER_PROPERTIES: |
        allow-cheats=true
        level-name=OsteBoys

    ports:
      - "25565:25565"
    volumes:
      - data:/data
      - ./modpacks:/modpacks:ro

volumes:
  data:
